"""empty message

Revision ID: 75fdfc3b0c3d
Revises: 
Create Date: 2025-12-21 19:40:58.244628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75fdfc3b0c3d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('blood_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('patient_name', sa.String(length=100), nullable=False),
    sa.Column('blood_type', sa.String(length=5), nullable=False),
    sa.Column('units_needed', sa.Integer(), nullable=False),
    sa.Column('urgency', sa.String(length=20), nullable=False),
    sa.Column('hospital', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('contact_name', sa.String(length=100), nullable=False),
    sa.Column('contact_phone', sa.String(length=20), nullable=False),
    sa.Column('contact_email', sa.String(length=120), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('donor_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('blood_type', sa.String(length=5), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('donor_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_donor_profiles_blood_type'), ['blood_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_donor_profiles_city'), ['city'], unique=False)
        batch_op.create_index(batch_op.f('ix_donor_profiles_is_available'), ['is_available'], unique=False)

    op.create_table('hospital_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('hospital_name', sa.String(length=100), nullable=False),
    sa.Column('registration_number', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hospital_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hospital_profiles_city'), ['city'], unique=False)
        batch_op.create_index(batch_op.f('ix_hospital_profiles_state'), ['state'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hospital_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hospital_profiles_state'))
        batch_op.drop_index(batch_op.f('ix_hospital_profiles_city'))

    op.drop_table('hospital_profiles')
    with op.batch_alter_table('donor_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_donor_profiles_is_available'))
        batch_op.drop_index(batch_op.f('ix_donor_profiles_city'))
        batch_op.drop_index(batch_op.f('ix_donor_profiles_blood_type'))

    op.drop_table('donor_profiles')
    op.drop_table('blood_requests')
    op.drop_table('users')
    # ### end Alembic commands ###
